name: build mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: read

    container:
      image: ghcr.io/minecraft-ros2/minecraft_ros2:latest

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 固定キーで Gradle キャッシュ
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: /root/.gradle
          key: gradle-cache

      # 固定キーで run ディレクトリキャッシュ
      - name: Cache Minecraft ROS2 run directory
        uses: actions/cache@v4
        with:
          path: ./run
          key: run-dir-cache

      - name: build mod
        run: |
          ./gradlew prepareRunClientCompile