name: build mod

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: read

    container:
      image: ghcr.io/minecraft-ros2/minecraft_ros2:latest

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: /root/.gradle
          key: gradle-cache

      - name: build mod
        run: |
          ./gradlew prepareRunClientCompile
      
      - name: remove big files
        run: |
          rm -rf /root/.gradle/daemon
          
