name: docker build pr

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/**'

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (PR)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false  # pushせずビルドだけ
          tags: |
            ghcr.io/minecraft-ros2/minecraft_ros2:pr-${{ github.event.pull_request.number }}
          labels: |
            org.opencontainers.image.title=minecraft_ros2
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
